parameters:
    hubspot.client.class: 'DocPlanner\Bundle\HubSpotBundle\Services\ProxyAwareFactory'
    hubspot.factory.class: 'DocPlanner\Bundle\HubSpotBundle\Services\ProxyAwareFactory'

services:
    hubspot:
        class: "%hubspot.client.class%"
        factory: ["%hubspot.factory.class%", 'createClient']
        arguments:
            - "@=parameter('hubspot')"
